import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Layout/Footer";
import Navbar from "@/components/Layout/Navbar";
import BackUpPage from "@/components/BackUpPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={inter.className}>
        <Navbar />
        {/* <Header /> */}
        <main className="flex-1">
          {children} <BackUpPage />
        </main>
        <Footer />
      </body>
    </html>
  );
}
